package com.xshopai.orderprocessor.security;

import com.xshopai.orderprocessor.client.DaprSecretManager;
import io.jsonwebtoken.Claims;
import io.jsonwebtoken.Jwts;
import io.jsonwebtoken.security.Keys;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.authority.SimpleGrantedAuthority;
import org.springframework.stereotype.Service;

import javax.crypto.SecretKey;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.function.Function;

/**
 * JWT Service for token validation and claims extraction
 * Compatible with tokens generated by auth-service (Node.js)
 * Uses Dapr Secret Manager to retrieve JWT secret with lazy loading
 * Algorithm and expiration are configurable via application.yml
 */
@Service
@Slf4j
public class JwtService {

    private final DaprSecretManager secretManager;
    private volatile SecretKey secretKey;
    
    @Value("${jwt.algorithm:HS256}")
    private String jwtAlgorithm;
    
    @Value("${jwt.expiration-seconds:3600}")
    private long jwtExpirationSeconds;
    
    @Value("${jwt.issuer:auth-service}")
    private String jwtIssuer;
    
    @Value("${jwt.audience:xshopai-platform}")
    private String jwtAudience;

    public JwtService(DaprSecretManager secretManager) {
        this.secretManager = secretManager;
        // Don't load secret in constructor - use lazy loading on first use
    }
    
    /**
     * Get configured JWT algorithm
     */
    public String getJwtAlgorithm() {
        return jwtAlgorithm;
    }
    
    /**
     * Get configured JWT expiration in seconds
     */
    public long getJwtExpirationSeconds() {
        return jwtExpirationSeconds;
    }

    /**
     * Get secret key with lazy initialization
     */
    private SecretKey getSecretKey() {
        if (secretKey == null) {
            synchronized (this) {
                if (secretKey == null) {
                    // Get JWT secret from Dapr Secret Store on first use
                    String secret = secretManager.getJwtSecret();
                    // Create secret key from configured secret
                    // Must match the JWT_SECRET used by auth-service
                    secretKey = Keys.hmacShaKeyFor(secret.getBytes(StandardCharsets.UTF_8));
                    log.info("JWT secret key initialized from Dapr");
                }
            }
        }
        return secretKey;
    }

    /**
     * Extract username (email) from JWT token
     */
    public String extractUsername(String token) {
        return extractClaim(token, claims -> claims.get("email", String.class));
    }

    /**
     * Extract user ID from JWT token
     */
    public String extractUserId(String token) {
        return extractClaim(token, claims -> claims.get("id", String.class));
    }

    /**
     * Extract roles from JWT token
     */
    @SuppressWarnings("unchecked")
    public List<String> extractRoles(String token) {
        return extractClaim(token, claims -> {
            Object rolesObj = claims.get("roles");
            if (rolesObj instanceof List) {
                return (List<String>) rolesObj;
            }
            return new ArrayList<>();
        });
    }

    /**
     * Convert roles to Spring Security authorities
     */
    public List<GrantedAuthority> extractAuthorities(String token) {
        List<String> roles = extractRoles(token);
        return roles.stream()
                .map(role -> new SimpleGrantedAuthority("ROLE_" + role.toUpperCase()))
                .map(auth -> (GrantedAuthority) auth)
                .toList();
    }

    /**
     * Extract expiration date from JWT token
     */
    public Date extractExpiration(String token) {
        return extractClaim(token, Claims::getExpiration);
    }

    /**
     * Extract a specific claim from JWT token
     */
    public <T> T extractClaim(String token, Function<Claims, T> claimsResolver) {
        final Claims claims = extractAllClaims(token);
        return claimsResolver.apply(claims);
    }

    /**
     * Extract all claims from JWT token with issuer and audience validation
     */
    private Claims extractAllClaims(String token) {
        return Jwts.parser()
                .verifyWith(getSecretKey())
                .requireIssuer(jwtIssuer)  // Validate issuer
                .requireAudience(jwtAudience)  // Validate audience
                .build()
                .parseSignedClaims(token)
                .getPayload();
    }

    /**
     * Check if token is expired
     */
    public Boolean isTokenExpired(String token) {
        return extractExpiration(token).before(new Date());
    }

    /**
     * Validate JWT token
     */
    public Boolean validateToken(String token) {
        try {
            return !isTokenExpired(token);
        } catch (Exception e) {
            log.error("JWT validation failed", e);
            return false;
        }
    }
}
